// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFN-u-eEIQPA1D5DsiJxE16QAHXZKUwh0',
    appId: '1:777598291360:web:4ac5f7bebc0d079d76e8c5',
    messagingSenderId: '777598291360',
    projectId: 'ecommerceapp-c26cd',
    authDomain: 'ecommerceapp-c26cd.firebaseapp.com',
    storageBucket: 'ecommerceapp-c26cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyoeil3QHNOmKdRck-aO5UzRvaA3dLzTk',
    appId: '1:777598291360:android:5739738a2dbdc23976e8c5',
    messagingSenderId: '777598291360',
    projectId: 'ecommerceapp-c26cd',
    storageBucket: 'ecommerceapp-c26cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj0X8Y5GstynFiITdsZx1TKDQBONym4cI',
    appId: '1:777598291360:ios:d0d1478dac07c2af76e8c5',
    messagingSenderId: '777598291360',
    projectId: 'ecommerceapp-c26cd',
    storageBucket: 'ecommerceapp-c26cd.appspot.com',
    androidClientId: '777598291360-8j33sg8nuobkmntuv2k1lvjtkot74mu6.apps.googleusercontent.com',
    iosClientId: '777598291360-dsvb6n1t0it8jabiqju67f5koidc8d0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}